# Generated by Django 4.1.2 on 2022-10-27 09:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_usertype', models.CharField(choices=[('ADMIN', 'ADMIN'), ('PATIENT', 'PATIENT'), ('CARETAKER', 'CARETAKER')], default='PATIENT', max_length=16)),
                ('Profile_birthdate', models.DateField()),
                ('Profile_gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=8)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Caretaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caretaker_since', models.DateField(default=datetime.date.today)),
                ('Caretaker_status', models.BooleanField(default=1)),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.profile')),
            ],
        ),
    ]
