# Generated by Django 4.1.3 on 2022-11-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Member_URLPic',
            field=models.URLField(blank=True, null=True),
        ),
    ]
