# Generated by Django 4.1.3 on 2022-11-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_member_member_urlpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Member_URLPic',
            field=models.URLField(default='https://t4.ftcdn.net/jpg/03/49/49/79/360_F_349497933_Ly4im8BDmHLaLzgyKg2f2yZOvJjBtlw5.jpg', max_length=250),
        ),
    ]
