# Generated by Django 4.1.2 on 2022-10-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_medicine_member_patient_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Member_token',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='Member_verified',
            field=models.BooleanField(default=False),
        ),
    ]
