# Generated by Django 4.1.3 on 2022-11-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_member_member_urlpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='Medicine_URLPic',
            field=models.URLField(default='https://cdn.pixabay.com/photo/2013/07/18/10/55/dna-163466_960_720.jpg', max_length=250),
        ),
    ]
