# Generated by Django 4.1.3 on 2022-12-10 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_medicine_medicine_urlpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.record'),
        ),
        migrations.AlterField(
            model_name='history',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.alert'),
        ),
    ]
