# Generated by Django 4.1.3 on 2022-12-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_alert_record_alter_history_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='History_takeDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='History_takeTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
